version: 2
jobs:
  deploy:
    machine:
      docker_layer_caching: true
    environment:
      BUILD_NUM: $CIRCLE_BUILD_NUM
    steps:
      - checkout
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: make build
      - run: make deploy

workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only: master